import ora from 'ora';
import chalk from 'chalk';
import { ArchitectureSchema } from '../parser.js';
import { createFile } from '../utils/fs.js';

export async function scaffoldProject(schema: ArchitectureSchema, targetDir: string) {
  const spinner = ora(`Scaffolding ${schema.framework} project in ${targetDir}...`).start();
  
  return new Promise((resolve) => {
    setTimeout(() => {
      spinner.stop();
      console.log(`\n📦 ${chalk.bold('Building Project Files:')}`);
      
      // Basic Package JSON
      createFile(`${targetDir}/package.json`, JSON.stringify({
        name: schema.name,
        version: "0.1.0",
        private: true,
        scripts: {
          "dev": "next dev",
          "build": "next build",
          "start": "next start"
        }
      }, null, 2));

      // README
      createFile(`${targetDir}/README.md`, `# ${schema.name}\n\nAuto-generated by Auto-Architect.\n\n### Tech Stack:\n- **Framework**: ${schema.framework}\n- **Database**: ${schema.database || 'None'}\n- **Styling**: ${schema.styling}\n- **CI/CD**: ${schema.ci || 'None'}\n- **Features**: ${schema.features.join(', ') || 'None'}`);

      // Framework specific files
      if (schema.framework === 'Next.js') {
        createFile(`${targetDir}/app/page.tsx`, `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-4xl font-bold">Welcome to ${schema.name}</h1>
      <p>Your AI-scaffolded Next.js app is ready!</p>
    </main>
  );
}`);
      }

      // Tailwind Setup
      if (schema.styling === 'Tailwind CSS') {
        createFile(`${targetDir}/tailwind.config.js`, `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [],
}`);
      }

      // CI Setup
      if (schema.ci === 'GitHub Actions') {
        createFile(`${targetDir}/.github/workflows/deploy.yml`, `name: Deploy\non: [push]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n      - run: npm install\n      - run: npm run build`);
      }

      console.log(chalk.green(`\n✨ Successfully generated ${schema.name}!`));
      console.log(chalk.cyan(`\nNext steps:\n  cd ${targetDir}\n  npm install\n  npm run dev`));
      
      resolve(true);
    }, 1200);
  });
}
